# Generated by Django 5.1 on 2024-11-20 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0003_alter_risk_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='risk_type',
            field=models.CharField(choices=[('Death', 'Death'), ('Car Accident', 'Car Accident'), ('Sickness', 'Sickness'), ('Business Failure', 'Business Failure')], max_length=50),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Resolved', 'Resolved')], default='Submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='risk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to=settings.AUTH_USER_MODEL),
        ),
    ]
