# Generated by Django 5.1 on 2024-11-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_alter_risk_risk_type_alter_risk_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Submitted', max_length=20),
        ),
    ]
