# Generated by Django 5.1.1 on 2024-11-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_address_alter_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('superadmin', 'superadmin')], default='user', max_length=10, verbose_name='role'),
        ),
    ]
